# Generated by Django 4.0.2 on 2022-02-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('userstate', models.IntegerField(default=0)),
                ('taskstate', models.IntegerField(default=0)),
                ('sleepstart', models.CharField(max_length=5)),
                ('sleepend', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('counts', models.IntegerField(default=0)),
                ('measure', models.CharField(max_length=20)),
                ('repper', models.IntegerField(default=0)),
                ('notitime', models.CharField(max_length=5)),
                ('notinext', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='based.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notitime', models.IntegerField(default=0)),
                ('multiply', models.IntegerField(default=0)),
                ('mess_id', models.IntegerField(default=0)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='based.task')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='based.user')),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstart', models.IntegerField(default=0)),
                ('tfinish', models.IntegerField(default=0)),
                ('human', models.CharField(max_length=200)),
                ('taskid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='based.task')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='based.user')),
            ],
        ),
    ]
