# Generated by Django 4.0.2 on 2022-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('based', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
